name: Quick Check

on:
  # Run on pull requests to main/master
  pull_request:
    branches: [ main, master ]
  
  # Run on pushes to main/master (for direct commits)
  push:
    branches: [ main, master ]
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run daily at 2 AM UTC for regular health checks
  schedule:
    - cron: '0 2 * * *'

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Run linting
      run: uv run ruff check .

    - name: Run tests
      run: uv run pytest --tb=short 